// 用户列表
const userList = [
  {
    id: "eec11929-3c60-497b-942c-92a3dd3eeeb5",
    userName: "cestc",
    displayName: "工程师",
    phone: "13801380138",
    roles: [
      {
        id: "2",
        name: "cestc"
      }
    ],
    lockFlag: 0
  }
];

// 角色列表
const roleList = [
  {
    name: "cestc",
    title: "工程师",
    description: "系统工程师，管理配置中心",
    menus: [
      { id: "page1" },
      { id: "page2" },
      { id: "home" },
      { id: "dict" },
      { id: "geological" },
      { id: "coordination" },
      { id: "geodesy" },
      { id: "measure" },
      { id: "hydrology" },
      { id: "measure" },
      { id: "graphical" },
      { id: "proofings" },
      { id: "ventilate" },
      { id: "network" },
      { id: "drill" },
      { id: "excavation" },
      { id: "section" },
      { id: "special" },
      { id: "mining" },
      { id: "designParam" },
      { id: "electric" },
      { id: "supply" },
      { id: "fixed" },
      { id: "geoManage" },
      { id: "geology" },
      { id: "survey" },
      { id: "production" },
      { id: "waterControl" },
      { id: "basic" },
      { id: "material" },
      { id: "design" },
      { id: "businessFlow" },
      { id: "technology" },
      { id: "proManage" },
      { id: "venManage" },
      { id: "gas" },
      { id: "outfire" },
      { id: "dustproof" },
      { id: "monitor" },
      { id: "dispatch" },
      { id: "proSituation" },
      { id: "wellEntry" },
      { id: "means" },
      { id: "duty" },
      { id: "sale" },
      { id: "analysis" },
      { id: "elecManage" },
      { id: "overhaul" },
      { id: "equipment" },
      { id: "security" },
      { id: "risk" },
      { id: "hiddDenDanger" },
      { id: "compreMon" },
      { id: "safety" },
      { id: "perLocation" },
      { id: "teamInfo" },
      { id: "monthPlan" },
      { id: "contractManage" },
      { id: "temLibrary" },
      { id: "archives" },
      { id: "personnel" },
      { id: "certicficates" },
      { id: "elecArchives" },
      { id: "elecArchivesManage" },
      { id: "bill" }
    ],
    users: [
      {
        id: "eec11929-3c60-497b-942c-92a3dd3eeeb5"
      }
    ],
    id: "2",
    parentId: "root"
  }
];

// 菜单列表
const menuList = [
  {
    id: "page1",
    name: "coordinateDesign",
    title: "协同设计",
    url: "coordinateDesign",
    path: "template",
    sort: 34,
    parentId: "rootMenu",
    parenetPath: "rootMenu",
    status: 1,
    description: "",
    ico: "md-cube",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "page2",
    name: "coordinateManage",
    title: "协同管理",
    url: "coordinateManage",
    path: "template",
    sort: 32,
    parentId: "rootMenu",
    parenetPath: "rootMenu",
    status: 1,
    description: "",
    ico: "md-settings",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "home",
    name: "home",
    title: "基础数据",
    url: "/home",
    path: "template",
    sort: 30,
    parentId: "page1",
    parenetPath: "page1",
    status: 1,
    description: "",
    ico: "md-analytics",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "dict",
    name: "data/dict",
    title: "数据字典",
    url: "data/dict",
    path: "template",
    sort: 28,
    parentId: "page1",
    parenetPath: "page1",
    status: 1,
    description: "",
    ico: "md-albums",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "geological",
    name: "geological",
    title: "地测协同",
    url: "geological",
    path: "",
    sort: 26,
    parentId: "page1",
    parenetPath: "page1",
    status: 1,
    description: "",
    ico: "md-archive",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "coordination",
    name: "coordination",
    title: "地理信息协同",
    url: "coordination",
    path: "template",
    sort: 10,
    parentId: "geological",
    parenetPath: "geological",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "geodesy",
    name: "geodesy",
    title: "地测数据信息",
    url: "geodesy",
    path: "template",
    sort: 8,
    parentId: "geological",
    parenetPath: "geological",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "measure",
    name: "measure",
    title: "测量数据库信息",
    url: "measure",
    path: "template",
    sort: 6,
    parentId: "geological",
    parenetPath: "geological",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "hydrology",
    name: "hydrology",
    title: "水文地质图形",
    url: "hydrology",
    path: "template",
    sort: 4,
    parentId: "geological",
    parenetPath: "geological",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "graphical",
    name: "graphical",
    title: "测量图形",
    url: "graphical",
    path: "template",
    sort: 2,
    parentId: "geological",
    parenetPath: "geological",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "proofings",
    name: "proofings",
    title: "一通三防",
    url: "proofings",
    path: "",
    sort: 24,
    parentId: "page1",
    parenetPath: "page1",
    status: 1,
    description: "",
    ico: "md-basket",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "draw",
    name: "draw",
    title: "系统图形绘制",
    url: "draw",
    path: "template",
    sort: 10,
    parentId: "proofings",
    parenetPath: "proofings",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "ventilate",
    name: "ventilate",
    title: "通风阻力测定",
    url: "ventilate",
    path: "template",
    sort: 8,
    parentId: "proofings",
    parenetPath: "proofings",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "network",
    name: "network",
    title: "通风网络解算",
    url: "network",
    path: "template",
    sort: 6,
    parentId: "proofings",
    parenetPath: "proofings",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "drill",
    name: "drill",
    title: "钻孔竣工图",
    url: "drill",
    path: "template",
    sort: 4,
    parentId: "proofings",
    parenetPath: "proofings",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "excavation",
    name: "excavation",
    title: "采掘辅助",
    url: "excavation",
    path: "",
    sort: 22,
    parentId: "page1",
    parenetPath: "page1",
    status: 1,
    description: "",
    ico: "ios-beaker",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "section",
    name: "section",
    title: "断面图设计",
    url: "section",
    path: "template",
    sort: 10,
    parentId: "excavation",
    parenetPath: "excavation",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "special",
    name: "special",
    title: "专用设计",
    url: "special",
    path: "template",
    sort: 8,
    parentId: "excavation",
    parenetPath: "excavation",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "mining",
    name: "mining",
    title: "采区设计",
    url: "mining",
    path: "template",
    sort: 6,
    parentId: "excavation",
    parenetPath: "excavation",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "designParam",
    name: "designParam",
    title: "设计参数",
    url: "designParam",
    path: "template",
    sort: 4,
    parentId: "excavation",
    parenetPath: "excavation",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "electric",
    name: "electric",
    title: "机电协同",
    url: "electric",
    path: "",
    sort: 20,
    parentId: "page1",
    parenetPath: "page1",
    status: 1,
    description: "",
    ico: "ios-clipboard",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "supply",
    name: "supply",
    title: "供电设备",
    url: "supply",
    path: "template",
    sort: 10,
    parentId: "electric",
    parenetPath: "electric",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "fixed",
    name: "fixed",
    title: "固定设备",
    url: "fixed",
    path: "template",
    sort: 8,
    parentId: "electric",
    parenetPath: "electric",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "geoManage",
    name: "geoManage",
    title: "地测管理",
    url: "geoManage",
    path: "",
    sort: 30,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-bookmarks",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "geology",
    name: "geology",
    title: "地质管理",
    url: "geology",
    path: "template",
    sort: 10,
    parentId: "geoManage",
    parenetPath: "geoManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "survey",
    name: "survey",
    title: "测量管理",
    url: "survey",
    path: "template",
    sort: 8,
    parentId: "geoManage",
    parenetPath: "geoManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "waterControl",
    name: "waterControl",
    title: "防治水管理",
    url: "waterControl",
    path: "template",
    sort: 6,
    parentId: "geoManage",
    parenetPath: "geoManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "production",
    name: "production",
    title: "生产技术",
    url: "production",
    path: "",
    sort: 28,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-briefcase",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "basic",
    name: "basic",
    title: "基础信息",
    url: "basic",
    path: "template",
    sort: 10,
    parentId: "production",
    parenetPath: "production",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "material",
    name: "material",
    title: "技术资料",
    url: "material",
    path: "template",
    sort: 8,
    parentId: "production",
    parenetPath: "production",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "design",
    name: "design",
    title: "设计管理",
    url: "design",
    path: "template",
    sort: 6,
    parentId: "production",
    parenetPath: "production",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "businessFlow",
    name: "businessFlow",
    title: "业务流",
    url: "businessFlow",
    path: "template",
    sort: 4,
    parentId: "production",
    parenetPath: "production",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "technology",
    name: "technology",
    title: "科技项目",
    url: "technology",
    path: "template",
    sort: 2,
    parentId: "production",
    parenetPath: "production",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "proManage",
    name: "proManage",
    title: "一通三防",
    url: "proManage",
    path: "",
    sort: 26,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-contrast",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "venManage",
    name: "venManage",
    title: "通风管理",
    url: "venManage",
    path: "template",
    sort: 10,
    parentId: "proManage",
    parenetPath: "proManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "gas",
    name: "gas",
    title: "防瓦斯管理",
    url: "gas",
    path: "template",
    sort: 8,
    parentId: "proManage",
    parenetPath: "proManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "outfire",
    name: "outfire",
    title: "防灭火管理",
    url: "outfire",
    path: "template",
    sort: 6,
    parentId: "proManage",
    parenetPath: "proManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "dustproof",
    name: "dustproof",
    title: "防尘管理",
    url: "dustproof",
    path: "template",
    sort: 4,
    parentId: "proManage",
    parenetPath: "proManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "monitor",
    name: "monitor",
    title: "监控管理",
    url: "monitor",
    path: "template",
    sort: 2,
    parentId: "proManage",
    parenetPath: "proManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "dispatch",
    name: "dispatch",
    title: "生产调度",
    url: "dispatch",
    path: "",
    sort: 24,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-arrow-dropright-circle",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "proSituation",
    name: "proSituation",
    title: "生产情况",
    url: "proSituation",
    path: "template",
    sort: 10,
    parentId: "dispatch",
    parenetPath: "dispatch",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "wellEntry",
    name: "wellEntry",
    title: "入井人数",
    url: "wellEntry",
    path: "template",
    sort: 8,
    parentId: "dispatch",
    parenetPath: "dispatch",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "means",
    name: "means",
    title: "技术资料",
    url: "means",
    path: "template",
    sort: 6,
    parentId: "dispatch",
    parenetPath: "dispatch",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "duty",
    name: "duty",
    title: "值跟班计划",
    url: "duty",
    path: "template",
    sort: 4,
    parentId: "dispatch",
    parenetPath: "dispatch",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "sale",
    name: "sale",
    title: "销售情况",
    url: "sale",
    path: "template",
    sort: 2,
    parentId: "dispatch",
    parenetPath: "dispatch",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "analysis",
    name: "analysis",
    title: "生产分析",
    url: "analysis",
    path: "template",
    sort: 0,
    parentId: "dispatch",
    parenetPath: "dispatch",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "elecManage",
    name: "elecManage",
    title: "机电管理",
    url: "elecManage",
    path: "",
    sort: 22,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-barcode",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "overhaul",
    name: "overhaul",
    title: "智能检修",
    url: "overhaul",
    path: "template",
    sort: 30,
    parentId: "elecManage",
    parenetPath: "elecManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "equipment",
    name: "equipment",
    title: "设备台账",
    url: "equipment",
    path: "template",
    sort: 28,
    parentId: "elecManage",
    parenetPath: "elecManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "security",
    name: "security",
    title: "安全管理",
    url: "security",
    path: "",
    sort: 20,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-checkbox",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "risk",
    name: "risk",
    title: "风险管理",
    url: "risk",
    path: "template",
    sort: 20,
    parentId: "security",
    parenetPath: "security",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "hiddDenDanger",
    name: "hiddDenDanger",
    title: "隐患管理",
    url: "hiddDenDanger",
    path: "template",
    sort: 18,
    parentId: "security",
    parenetPath: "security",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "compreMon",
    name: "compreMon",
    title: "综合监测",
    url: "compreMon",
    path: "",
    sort: 18,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-grid",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "safety",
    name: "safety",
    title: "安全监控",
    url: "safety",
    path: "template",
    sort: 30,
    parentId: "compreMon",
    parenetPath: "compreMon",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "perLocation",
    name: "perLocation",
    title: "人员位置",
    url: "perLocation",
    path: "template",
    sort: 28,
    parentId: "compreMon",
    parenetPath: "compreMon",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "teamInfo",
    name: "teamInfo",
    title: "区队信息",
    url: "teamInfo",
    path: "",
    sort: 16,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-list",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "monthPlan",
    name: "monthPlan",
    title: "月度计划",
    url: "monthPlan",
    path: "template",
    sort: 10,
    parentId: "teamInfo",
    parenetPath: "teamInfo",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "contractManage",
    name: "contractManage",
    title: "合同管理",
    url: "contractManage",
    path: "",
    sort: 14,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-paper",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "temLibrary",
    name: "temLibrary",
    title: "合同模板库",
    url: "temLibrary",
    path: "template",
    sort: 10,
    parentId: "contractManage",
    parenetPath: "contractManage",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "archives",
    name: "archives",
    title: "培训档案",
    url: "archives",
    path: "",
    sort: 12,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-filing",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "personnel",
    name: "personnel",
    title: "人员培训",
    url: "personnel",
    path: "template",
    sort: 10,
    parentId: "archives",
    parenetPath: "archives",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "certicficates",
    name: "certicficates",
    title: "证件管理",
    url: "certicficates",
    path: "template",
    sort: 8,
    parentId: "archives",
    parenetPath: "archives",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "elecArchives",
    name: "elecArchives",
    title: "电子档案",
    url: "elecArchives",
    path: "",
    sort: 10,
    parentId: "page2",
    parenetPath: "page2",
    status: 1,
    description: "",
    ico: "md-photos",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "elecArchivesManage",
    name: "elecArchivesManage",
    title: "电子档案",
    url: "elecArchivesManage",
    path: "template",
    sort: 10,
    parentId: "elecArchives",
    parenetPath: "elecArchives",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  },
  {
    id: "bill",
    name: "bill",
    title: "财务票据",
    url: "bill",
    path: "template",
    sort: 8,
    parentId: "elecArchives",
    parenetPath: "elecArchives",
    status: 1,
    description: "",
    ico: "",
    isOutSide: false,
    showLevel: 3
  }
];

// 菜单层级
const menuLevel = [
  {
    label: "菜单显示该页面选项，页面不含菜单栏不含面包屑",
    value: "1"
  },
  {
    label: "菜单显示该页面选项，页面含菜单栏但不含面包屑",
    value: "2"
  },
  {
    label: "菜单显示该页面选项，页面含菜单栏和面包屑",
    value: "3"
  },
  {
    label: "菜单隐藏该页面选项，页面不含菜单栏不含面包屑",
    value: "4"
  }
];

export { userList, roleList, menuList, menuLevel };
